# This file was generated by GoReleaser. DO NOT EDIT.
cask "files2prompt" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "55835aa95a4ea2c7ed29651a22edb35d318313f09dd2e3cbccff59cfc18bfa07"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "f3ed06123a96a1f619aaed319cf81fd13d3057015565b13048e94db3682d939a"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2183d4549641bbe6f52ce29268f8286d7ed7f8cc5c6cf5928a2ff193ae5c802"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "e92467fcd9249072dfd0b0a6ee8d678b22dedc9601d1157fdd31462a54392658"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "files2prompt"
  desc "LLM Prompt Generator From Local Files"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "files2prompt"
  manpage "manpages/files2prompt.1.gz"
  bash_completion "completions/files2prompt.bash"
  fish_completion "completions/files2prompt.fish"
  zsh_completion "completions/files2prompt.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/files2prompt"]
    end
  end

  # No zap stanza required

end
