# This file was generated by GoReleaser. DO NOT EDIT.
cask "files2prompt" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "162bbce940121e60c369aea30a8a1ddacf98ce8ae444577783e1148e59c9cf29"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "eb2147d07c5d9bdba4219b92eca808391655a51f2c125dfe201eeacbee953fef"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "3789552952b982c59bb40fc9530d87afb44b95d746ed56168d4dedb7ed6a50e6"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "71b137d4b346d2e7147cccdeec159ecd150e730afb819154bf31e344eff5aba3"
      url "https://github.com/toozej/monogo/releases/download/apps/files2prompt/v#{version}/files2prompt_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "files2prompt"
  desc "LLM Prompt Generator From Local Files"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "files2prompt"
  manpage "manpages/files2prompt.1.gz"
  bash_completion "completions/files2prompt.bash"
  fish_completion "completions/files2prompt.fish"
  zsh_completion "completions/files2prompt.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/files2prompt"]
    end
  end

  # No zap stanza required

end
