# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghreleases2rss" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "086127cd1d8241f24b0e549eac4737b37ad2f9bd727b7b779b8e42b1d08cebe3"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "de72cad074756231cc383cef3c5b114d8a2325b352905bfe06cf75495d6c73d4"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "817ccf67b99e38e64d72010cc1b274646404c01e74dd56f9423bdd03c3a432e5"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "ea21807d8ed48b72939cc8c0e10e361edeca4792e8af55dfc3863b3056284d05"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "ghreleases2rss"
  desc "Subscribe to GitHub projects’ releases in RSS reader"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghreleases2rss"
  manpage "manpages/ghreleases2rss.1.gz"
  bash_completion "completions/ghreleases2rss.bash"
  fish_completion "completions/ghreleases2rss.fish"
  zsh_completion "completions/ghreleases2rss.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghreleases2rss"]
    end
  end

  # No zap stanza required

end
