# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghreleases2rss" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "5833bd23e95bc36f3ba47164731a59a8ecf079a34d2008c3b132dc1d38d51f6b"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "28bba843d1ae502add74a653cb9831b44eb4006f14b0017229865ba3cc17df79"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "b1621a3e191c687ffbb7a1ab9b3d8e5bea438d78c5d18e1be8f92d176f915362"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "f6b194f3a36a703327121b9182b9d412887b66f1ac872c1bef2460d620c31266"
      url "https://github.com/toozej/monogo/releases/download/apps/ghreleases2rss/v#{version}/ghreleases2rss_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "ghreleases2rss"
  desc "Subscribe to GitHub projects’ releases in RSS reader"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghreleases2rss"
  manpage "manpages/ghreleases2rss.1.gz"
  bash_completion "completions/ghreleases2rss.bash"
  fish_completion "completions/ghreleases2rss.fish"
  zsh_completion "completions/ghreleases2rss.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghreleases2rss"]
    end
  end

  # No zap stanza required

end
