# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghreleases2rss" do
  name "ghreleases2rss"
  desc "Find liquor stores and their inventory"
  homepage "https://github.com/toozej/ghreleases2rss"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghreleases2rss"
  manpage "man/ghreleases2rss.1.gz"
  bash_completion "completions/ghreleases2rss.bash"
  zsh_completion "completions/ghreleases2rss.zsh"
  fish_completion "completions/ghreleases2rss.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/ghreleases2rss/releases/download/v#{version}/ghreleases2rss_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/ghreleases2rss/releases/download"
      sha256 "e20d882ab6b4f11eafed3495da043c57f33c5183eb8619734aa2127494ddffa2"
    end
    on_arm do
      url "https://github.com/toozej/ghreleases2rss/releases/download/v#{version}/ghreleases2rss_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/ghreleases2rss/releases/download"
      sha256 "03573cad95b02d61859dc6f14afd8d7a35bc557f83f4764c1da6328d1ca2e3ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/ghreleases2rss/releases/download/v#{version}/ghreleases2rss_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/ghreleases2rss/releases/download"
      sha256 "b8bbc91a5a4558ddd31fb9217919fb961b29787c000c442fbcdf0a861418aa0b"
    end
    on_arm do
      url "https://github.com/toozej/ghreleases2rss/releases/download/v#{version}/ghreleases2rss_Linux_arm64.tar.gz",
        verified: "github.com/toozej/ghreleases2rss/releases/download"
      sha256 "ff35c2862a2f8bba49982c4597ce2371519bac9e28d3aa0cfd89c8ab6b97bfa6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghreleases2rss"]
    end
  end

  # No zap stanza required
end
