# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-castctl" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "1cb72668c033a140e3cd1c4f6bd349e3b08c9ae88eec6dddf87456ffe65a8890"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "e3f076585f820f91fad32eb894a0f31eb4ef6ccf7e5cf57abe76ec60de2e2968"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d839d551abb16444699f5b6b40c925ef2bfac4121c59e43cb746a35f85ad503"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "c77f6c6874825ea2a35df36dc4d3efc188d1ccfbe4278d755225d1bdb9f2466c"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "go-castctl"
  desc "Chromecast streaming website powered by Castor and go-app"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-castctl"
  manpage "manpages/go-castctl.1.gz"
  bash_completion "completions/go-castctl.bash"
  fish_completion "completions/go-castctl.fish"
  zsh_completion "completions/go-castctl.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-castctl"]
    end
  end

  # No zap stanza required

end
