# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-castctl" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "8105eb77cae4203dd101d75291886f987c4c5fcd16e35ea1f57a19fb4a182eb1"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "04565b9fc72512ca3de9347b1d523f900c980eb6e92daffcb8174892d12f7a83"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "b016cc47001514757c8287ae7a3e806fd8e18bea9bccbd9309a5e7cde4d0c72b"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "a19f2d33ae56dc9e4df01332bac6fafb3df88ffcc189f5107acd7686c101aa7d"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "go-castctl"
  desc "Chromecast streaming website powered by Castor and go-app"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-castctl"
  manpage "manpages/go-castctl.1.gz"
  bash_completion "completions/go-castctl.bash"
  fish_completion "completions/go-castctl.fish"
  zsh_completion "completions/go-castctl.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-castctl"]
    end
  end

  # No zap stanza required

end
