# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-castctl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c39cedbb5992d95f91fdf32659cc5a524acfe32a05f08f442d29267cfc653718"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "e6d3a8d83d9e1a51402b8f8cd895776d3127a7632691102bd6228f129af205f2"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ec3bc407298a797b7c10c916ffcd09fcc11b2a598abe69c477cd69e600b0788"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "fe7975aaf1e1e3f1b81d0e85f015398f507eaf94b25b0f36aae42777e0a84f70"
      url "https://github.com/toozej/monogo/releases/download/apps/go-castctl/v#{version}/go-castctl_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "go-castctl"
  desc "Chromecast streaming website powered by Castor and go-app"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-castctl"
  manpage "manpages/go-castctl.1.gz"
  bash_completion "completions/go-castctl.bash"
  fish_completion "completions/go-castctl.fish"
  zsh_completion "completions/go-castctl.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-castctl"]
    end
  end

  # No zap stanza required

end
