# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-find-archived-gh-actions" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c9cd9fad855a1e9a4c7469b3ece2fcb86e8761135aef24012d4a9f1f4bd90b8c"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
    on_arm do
      sha256 "9532726164aac0d6d575bac9fd2ecf9bb95ebbeb638f83dbdd37bbdd56373c26"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "76137dee33cdefe0eaf32afef325c6d5252d0a28d02129416028705d2df889f0"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
    on_arm do
      sha256 "125fd9e0190956c0cbb2dc07ef17f49fea519d91c978a512371c69df295657e1"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
  end

  name "go-find-archived-gh-actions"
  desc "Find archived GitHub Actions in use in GHA Workflows with optional notifications and GH Issue creation"
  homepage "https://github.com/toozej/go-find-archived-gh-actions"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-find-archived-gh-actions"
  manpage "manpages/go-find-archived-gh-actions.1.gz"
  bash_completion "completions/go-find-archived-gh-actions.bash"
  fish_completion "completions/go-find-archived-gh-actions.fish"
  zsh_completion "completions/go-find-archived-gh-actions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-find-archived-gh-actions"]
    end
  end

  # No zap stanza required

end
