# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-find-liquor" do
  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "8499f57fc0c8b2e7ea3b2b3ef31b7bc24031822afd85ea646f764744d0ad2c7b"
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
    end
    on_arm do
      sha256 "f92d9806c52cd796253f0be03b1bf321798a9f6fcda31305122f3f772638423a"
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "f19cdd9ae721734589e35a12d92b35543bfcaf308a5f9f19c3d78707408f83df"
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
    end
    on_arm do
      sha256 "1b752596ddd3e3c6a0a65bc38a28fc16ef965b23fcb481db7e13207806539401"
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
    end
  end

  name "go-find-liquor"
  desc "Oregon Liquor Search Notification Service"
  homepage "https://github.com/toozej/go-find-liquor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-find-liquor"
  manpage "manpages/go-find-liquor.1.gz"
  bash_completion "completions/go-find-liquor.bash"
  fish_completion "completions/go-find-liquor.fish"
  zsh_completion "completions/go-find-liquor.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-find-liquor"]
    end
  end

  # No zap stanza required

end
