# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-find-liquor" do
  name "go-find-liquor"
  desc "Oregon Liquor Search Notification Service"
  homepage "https://github.com/toozej/go-find-liquor"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-find-liquor"
  manpage "man/go-find-liquor.1.gz"
  bash_completion "completions/go-find-liquor.bash"
  zsh_completion "completions/go-find-liquor.zsh"
  fish_completion "completions/go-find-liquor.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "a9c760d3fa4f4bae7a969737bbfa5561e5c15c110bf41629bc429b4164aa1a2f"
    end
    on_arm do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "5d662f9a8fca543966e3120bf4a799e6f290a0aa97e7f6137c6fa42863d2044f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "7b28b5714e169212124de8e92c4a4c100e84ff23c8895400f5a9e21983c14cc7"
    end
    on_arm do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "1cf58f18378b09179772ac1d0dc06b1f89d3763ada61f4a2642fedcd290f89fd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-find-liquor"]
    end
  end

  # No zap stanza required
end
