# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-find-liquor" do
  name "go-find-liquor"
  desc "Oregon Liquor Search Notification Service"
  homepage "https://github.com/toozej/go-find-liquor"
  version "1.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-find-liquor"
  manpage "man/go-find-liquor.1.gz"
  bash_completion "completions/go-find-liquor.bash"
  zsh_completion "completions/go-find-liquor.zsh"
  fish_completion "completions/go-find-liquor.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "03597f3c6d409bbaed317e4a42bcbe1eb46f8a6c82f849aa127af6004075d736"
    end
    on_arm do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "2521488d4dfc54f5b377333c33e9599455343eb807aabdcac2a3bce3a5646768"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "368775fa33c1710ded453bd302dc650cfaa01156bfd297aefd03b6bc733190e5"
    end
    on_arm do
      url "https://github.com/toozej/go-find-liquor/releases/download/v#{version}/go-find-liquor_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-find-liquor/releases/download"
      sha256 "8753c29728f7814ceb369c56728068ecaf98863a210091a35c33a7065d2672fb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-find-liquor"]
    end
  end

  # No zap stanza required
end
