# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-find-archived-gh-actions" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7b632aa0f9ce7f55e946b5bbe1e13fe1d693a3321d8982a0b27632ee79b2c9c6"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
    on_arm do
      sha256 "51a7300b3dc72ad176131bdd42eb841d1bf1da64b477dedcec8b5b7313b61a64"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "f22ee6655475615e1833cd560774614a443619496987052af681bebf7974762a"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
    on_arm do
      sha256 "056ebc8882fc5be8536ca4720cb9717be3559afb562b7da3bdd5d0626e92b49a"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
  end

  name "go-find-archived-gh-actions"
  desc "Find archived GitHub Actions in use in GHA Workflows with optional notifications and GH Issue creation"
  homepage "https://github.com/toozej/go-find-archived-gh-actions"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-find-archived-gh-actions"
  manpage "manpages/go-find-archived-gh-actions.1.gz"
  bash_completion "completions/go-find-archived-gh-actions.bash"
  fish_completion "completions/go-find-archived-gh-actions.fish"
  zsh_completion "completions/go-find-archived-gh-actions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-find-archived-gh-actions"]
    end
  end

  # No zap stanza required

end
