# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-find-archived-gh-actions" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "167e8cf403d280d64731a7b18315bdc052c0648b3abd65f8ceac2b4015345a76"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
    on_arm do
      sha256 "aaabfbf46221be386612708326832a9883c058c96d2c4cb6c63bb31322fc72bf"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff77d3cedb7a368b216021f2e6fd74f47e779c129a349c52dab98022c6df2e7b"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
    on_arm do
      sha256 "cb542024225da1ce5da425b4170c6108d8e2e23a696330ee92920483e8c1895a"
      url "https://github.com/toozej/go-find-archived-gh-actions/releases/download/v#{version}/go-find-archived-gh-actions_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-find-archived-gh-actions/releases/download"
    end
  end

  name "go-find-archived-gh-actions"
  desc "Find archived GitHub Actions in use in GHA Workflows with optional notifications and GH Issue creation"
  homepage "https://github.com/toozej/go-find-archived-gh-actions"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-find-archived-gh-actions"
  manpage "manpages/go-find-archived-gh-actions.1.gz"
  bash_completion "completions/go-find-archived-gh-actions.bash"
  fish_completion "completions/go-find-archived-gh-actions.fish"
  zsh_completion "completions/go-find-archived-gh-actions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-find-archived-gh-actions"]
    end
  end

  # No zap stanza required

end
