# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-listen" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "f3b261070abfabfecf346805bbf1624021de98faf3696651ab969a9fb8e40851"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "45fd6e76ab4373eb872f0494f14143d49e6947c08260ce69ca4ab8d6a8748f3e"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "a4acde1ffef04f08f3bd68878dcf559e85c6c26f905539f3ad496700f8fbe2a9"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "69cc12ce6a726a6639acea58febd67b3d8ba6aa2b1c9b85a5b3cfb78117e5a3e"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "go-listen"
  desc "go-listen is a web application that allows users to search for artists and automatically add their top 5 songs to designated "incoming" playlists on Spotify"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-listen"
  manpage "manpages/go-listen.1.gz"
  bash_completion "completions/go-listen.bash"
  fish_completion "completions/go-listen.fish"
  zsh_completion "completions/go-listen.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-listen"]
    end
  end

  # No zap stanza required

end
