# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-listen" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "a31f3b1ef85929301b16e92eb9d1b0404112235623c591ee9959a0886e0aa86f"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "9324f7510c091e4778b26fe6431c946ca2cd11b566666505853d91095a21888f"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "b3687586cfcc6118974701872f73d73408ec04d2c249ba6b7100f04bf2af8d2e"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "fb12441b308d5a56ac9a8eef70af05155e7b7233fa1dbc4c0d52cea8e6a413d0"
      url "https://github.com/toozej/monogo/releases/download/apps/go-listen/v#{version}/go-listen_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "go-listen"
  desc "go-listen is a web application that allows users to search for artists and automatically add their top 5 songs to designated "incoming" playlists on Spotify"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-listen"
  manpage "manpages/go-listen.1.gz"
  bash_completion "completions/go-listen.bash"
  fish_completion "completions/go-listen.fish"
  zsh_completion "completions/go-listen.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-listen"]
    end
  end

  # No zap stanza required

end
