# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-listen" do
  name "go-listen"
  desc "go-listen is a web application that allows users to search for artists and automatically add their top 5 songs to designated incoming playlists on Spotify"
  homepage "https://github.com/toozej/go-listen"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-listen"
  manpage "man/go-listen.1.gz"
  bash_completion "completions/go-listen.bash"
  zsh_completion "completions/go-listen.zsh"
  fish_completion "completions/go-listen.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/go-listen/releases/download/v#{version}/go-listen_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-listen/releases/download"
      sha256 "da2f915f20637b1e5f64f85a25ef092974ab9bbe05ecb06777c08e6a181e1732"
    end
    on_arm do
      url "https://github.com/toozej/go-listen/releases/download/v#{version}/go-listen_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-listen/releases/download"
      sha256 "718ae48f7410756394db9d3c61e570ba3b9d7accce9642ffb6ee25cc9b8f79b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/go-listen/releases/download/v#{version}/go-listen_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-listen/releases/download"
      sha256 "8528e7416164e034dc7c58f311065fa5ecd090bc9fc4ad8dc94ad671e495e3de"
    end
    on_arm do
      url "https://github.com/toozej/go-listen/releases/download/v#{version}/go-listen_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-listen/releases/download"
      sha256 "8b00fd1aeea4c24f73406df3617f52d397c425ea106eeb597dfdf1a631c12ccb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-listen"]
    end
  end

  # No zap stanza required
end
