# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-sort-out-gh-actions" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "a6cd16b159a1a23e7855a3a01f808b49f8174fc37859a2f1f3fa38922810b090"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "f24472d984b79b4c1c4e23af4a44d01a29f43a47a22f6839c413a5e52254aadb"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1d2121de9e5522aaf8a7074446cc8b54fb10e5620717e577a60521048179a4b"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "8da2550a6fce2a74af159bc6cd0e62fa54bb1ac1807854d4937247e88efb84da"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "go-sort-out-gh-actions"
  desc "Find archived, outdated, EOL runtime GitHub Actions in use in GHA Workflows with optional notifications, auto-updates, pinning, and GH Issue creation"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-sort-out-gh-actions"
  manpage "manpages/go-sort-out-gh-actions.1.gz"
  bash_completion "completions/go-sort-out-gh-actions.bash"
  fish_completion "completions/go-sort-out-gh-actions.fish"
  zsh_completion "completions/go-sort-out-gh-actions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-sort-out-gh-actions"]
    end
  end

  # No zap stanza required

end
