# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-sort-out-gh-actions" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "6eed0aecc6188440e7ce93a6ca04c0c05809f8eec41927b68be053f365e9b33d"
      url "https://github.com/toozej/go-sort-out-gh-actions/releases/download/v#{version}/go-sort-out-gh-actions_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/go-sort-out-gh-actions/releases/download"
    end
    on_arm do
      sha256 "2e38c7771c7112649683b6246d8e908a2e2e01da1bcd6c660318b74ec644bb88"
      url "https://github.com/toozej/go-sort-out-gh-actions/releases/download/v#{version}/go-sort-out-gh-actions_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/go-sort-out-gh-actions/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c23f6e862c33512961877cb9a1ad9f926176db51f5f9db672ff99f772546791"
      url "https://github.com/toozej/go-sort-out-gh-actions/releases/download/v#{version}/go-sort-out-gh-actions_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/go-sort-out-gh-actions/releases/download"
    end
    on_arm do
      sha256 "f1b6d7fe5b8e2b745a5676e4f7626cc6445b39ad22c2cad73b882d09fd7c409b"
      url "https://github.com/toozej/go-sort-out-gh-actions/releases/download/v#{version}/go-sort-out-gh-actions_Linux_arm64.tar.gz",
        verified: "github.com/toozej/go-sort-out-gh-actions/releases/download"
    end
  end

  name "go-sort-out-gh-actions"
  desc "Find archived GitHub Actions in use in GHA Workflows with optional notifications and GH Issue creation"
  homepage "https://github.com/toozej/go-sort-out-gh-actions"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-sort-out-gh-actions"
  manpage "manpages/go-sort-out-gh-actions.1.gz"
  bash_completion "completions/go-sort-out-gh-actions.bash"
  fish_completion "completions/go-sort-out-gh-actions.fish"
  zsh_completion "completions/go-sort-out-gh-actions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-sort-out-gh-actions"]
    end
  end

  # No zap stanza required

end
