# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-sort-out-gh-actions" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "f54a214f10ba825fba2cd481b643ebb6f634b95c450c7c91e10dcc415f281693"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "78c0544b0e81a3d8665aa2689beb6df56561db139333ea1a936cc307ca22601e"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "033b194f600127e9e77a96dcb962eeba8d3429e75cccbcd525a89f69fb583f7b"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "d51e35b9789f0fe71c29f0ab8b73f5dc01966217fa48ae488d351e296387c1ed"
      url "https://github.com/toozej/monogo/releases/download/apps/go-sort-out-gh-actions/v#{version}/go-sort-out-gh-actions_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "go-sort-out-gh-actions"
  desc "Find archived, outdated, EOL runtime GitHub Actions in use in GHA Workflows with optional notifications, auto-updates, pinning, and GH Issue creation"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-sort-out-gh-actions"
  manpage "manpages/go-sort-out-gh-actions.1.gz"
  bash_completion "completions/go-sort-out-gh-actions.bash"
  fish_completion "completions/go-sort-out-gh-actions.fish"
  zsh_completion "completions/go-sort-out-gh-actions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-sort-out-gh-actions"]
    end
  end

  # No zap stanza required

end
