# This file was generated by GoReleaser. DO NOT EDIT.
cask "golang-starter" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "87b2a7e250fc7b1caf7260133e7be2c4da40d75cf072676bfaf7113cf9bf083d"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "2c954d59215cbc7dde3a6412cbdb26a2dffef32a4766893bf0ac75a8b9d00062"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "4fb5ad49dc79443855fc82a8aa15b4d383dac6660ed6b73c8a5eb26317f37bd8"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "301e41d6fbc3eb66a09dc0ef6695a0233b703aaf786ba2fc49f59c4fb4dd858b"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "golang-starter"
  desc "Golang starter app"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golang-starter"
  manpage "manpages/golang-starter.1.gz"
  bash_completion "completions/golang-starter.bash"
  fish_completion "completions/golang-starter.fish"
  zsh_completion "completions/golang-starter.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/golang-starter"]
    end
  end

  # No zap stanza required

end
