# This file was generated by GoReleaser. DO NOT EDIT.
cask "golang-starter" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3840518b8decdca2f0575e1f11ca03dc33d4ec57df2743fd957cf8ed77cd6465"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "c726c33b99cd798c8478779e347adff2047887900a710db6c9559c27f525434a"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f6365a5041b625f1be2956b659abfa8f0f1d7d1229cfc7b7e57ed80ed1dfd76"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "53a5fc36d76cf00e76f0f170df790246f94caf0d49df5fac2c8d6e59a11227a1"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "golang-starter"
  desc "Golang starter app"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golang-starter"
  manpage "manpages/golang-starter.1.gz"
  bash_completion "completions/golang-starter.bash"
  fish_completion "completions/golang-starter.fish"
  zsh_completion "completions/golang-starter.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/golang-starter"]
    end
  end

  # No zap stanza required

end
