# This file was generated by GoReleaser. DO NOT EDIT.
cask "golang-starter" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "0b77281b2d3da03b0e2e67331ee59d953ad5cb95d5987ec6292e8ccd6dcef21d"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "408d03aac158e9b1767c93409d3c7b72e4830d10947129e69999d1f011b543d8"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "c53a6ba7cd6ee89cfc8f7b39feddbdb61acfddcbee8a558b0fe0d375214b61b6"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "bbcf0dd4edb060b2ab1f7995cb6ffe727e08c677baac2e266439644eea1e4785"
      url "https://github.com/toozej/monogo/releases/download/apps/golang-starter/v#{version}/golang-starter_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "golang-starter"
  desc "Golang starter app"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golang-starter"
  manpage "manpages/golang-starter.1.gz"
  bash_completion "completions/golang-starter.bash"
  fish_completion "completions/golang-starter.fish"
  zsh_completion "completions/golang-starter.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/golang-starter"]
    end
  end

  # No zap stanza required

end
