# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotts-it" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "b0e759820d7ae7e88ce3801f6228ad58d6d040d285a58992d2927c41d7a5a685"
      url "https://github.com/toozej/monogo/releases/download/apps/gotts-it/v#{version}/gotts-it_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "f24a80f5c79d5c44e56836dfc8b6cda78b76a6729752ca7795c0b24b9c615079"
      url "https://github.com/toozej/monogo/releases/download/apps/gotts-it/v#{version}/gotts-it_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "379fd98c07d5e1e461b0f7640c606d2eb03f2f4fcb9920f6ee61fe7eaeb5eb8f"
      url "https://github.com/toozej/monogo/releases/download/apps/gotts-it/v#{version}/gotts-it_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "3d6d2142db9868efea30d36ffb42efa900e40d461f42f9d0b95769303d647cf8"
      url "https://github.com/toozej/monogo/releases/download/apps/gotts-it/v#{version}/gotts-it_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "gotts-it"
  desc "Go-based Text-To-Speech Tool"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gotts-it"
  manpage "manpages/gotts-it.1.gz"
  bash_completion "completions/gotts-it.bash"
  fish_completion "completions/gotts-it.fish"
  zsh_completion "completions/gotts-it.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gotts-it"]
    end
  end

  # No zap stanza required

end
