# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotts-it" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "ee3f7c39ca1e64105f869c5d6700c5a75eb6170d79f3f0e8012ce2cfea3c47bb"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
    on_arm do
      sha256 "3440a9fb4e53fdf11e4fe48cea33a49433d800d50be14e4511249c80c9605eb0"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0cddf08a589b1157f5557ff284e427587c3d37652fbddc6fb07e30b6ffb0ac1"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
    on_arm do
      sha256 "960b1dc3f1779a573a5c675ed6659286cbc2493bb30c3f804cc4a9b9365d1bbe"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Linux_arm64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
  end

  name "gotts-it"
  desc "Convert text (URL, text file) to speech"
  homepage "https://github.com/toozej/gotts-it"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gotts-it"
  manpage "manpages/gotts-it.1.gz"
  bash_completion "completions/gotts-it.bash"
  fish_completion "completions/gotts-it.fish"
  zsh_completion "completions/gotts-it.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gotts-it"]
    end
  end

  # No zap stanza required

end
