# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotts-it" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "822fca72cd2770e1e29e50c082d2b9586dba6e7b7e509cf12b57a35c28300edf"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
    on_arm do
      sha256 "8d39bba88b644bb2484c1f389bdf852947d0c1f36f4f21f00d0db7513d01d299"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "dfdc6ffb351d4503e6c2476de25313fb69d0e6e3098b4b7b0db900c45ee244a8"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
    on_arm do
      sha256 "b337d29e4bd4a59582c1e8eb4c716b0b0235d6d3ba32f6eb6edc104ff3026317"
      url "https://github.com/toozej/gotts-it/releases/download/v#{version}/gotts-it_Linux_arm64.tar.gz",
        verified: "github.com/toozej/gotts-it/releases/download"
    end
  end

  name "gotts-it"
  desc "Convert text (URL, text file) to speech"
  homepage "https://github.com/toozej/gotts-it"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gotts-it"
  manpage "manpages/gotts-it.1.gz"
  bash_completion "completions/gotts-it.bash"
  fish_completion "completions/gotts-it.fish"
  zsh_completion "completions/gotts-it.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gotts-it"]
    end
  end

  # No zap stanza required

end
