# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmhd2spotify" do
  name "kmhd2spotify"
  desc "Golang starter template"
  homepage "https://github.com/toozej/kmhd2spotify"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmhd2spotify"
  manpage "man/kmhd2spotify.1.gz"
  bash_completion "completions/kmhd2spotify.bash"
  zsh_completion "completions/kmhd2spotify.zsh"
  fish_completion "completions/kmhd2spotify.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "d711522f11eeb59f2b4fd335a7b8c6ada0cb65f2660de63e6a94c55a82eaa147"
    end
    on_arm do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "b71b77bf479219055ef28f5c2c153630de756ff914549497e8103370b2d25270"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "ff64190dc28ceaefbf5b24a2e050e23fe0c345371be03733a698b106ab23f8fb"
    end
    on_arm do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Linux_arm64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "0cbd6e2b45865fde6344d33b07a56638744e1eab67ad224db953031a53de7312"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmhd2spotify"]
    end
  end

  # No zap stanza required
end
