# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmhd2playlist" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "154087e5d531df39530e1115e1d6bbbb53bc4438a8fd949b30555e0a442bc744"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "7c883b135220202a75be6f060ed733b5f142ad3ae129c440d26d5d13ae3c2612"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "f21966c3ba7ce4cc7ab83fa111313403028f08e9b04f0b403c521e1ba6c24468"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "fd806f585ff09c89aaaa70a0b5fc211ddcad77ba8b839ca688afb1c68ad16e54"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "kmhd2playlist"
  desc "Automatically sync songs from KMHD jazz radio to your Spotify playlists"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmhd2playlist"
  manpage "manpages/kmhd2playlist.1.gz"
  bash_completion "completions/kmhd2playlist.bash"
  fish_completion "completions/kmhd2playlist.fish"
  zsh_completion "completions/kmhd2playlist.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmhd2playlist"]
    end
  end

  # No zap stanza required

end
