# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmhd2spotify" do
  name "kmhd2spotify"
  desc "Golang starter template"
  homepage "https://github.com/toozej/kmhd2spotify"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmhd2spotify"
  manpage "man/kmhd2spotify.1.gz"
  bash_completion "completions/kmhd2spotify.bash"
  zsh_completion "completions/kmhd2spotify.zsh"
  fish_completion "completions/kmhd2spotify.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "3d65185643ed955726161145b06f7407a550001f421a6f9d81fab0100d14263f"
    end
    on_arm do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "a7656b807aa46dc30adf2d78ec49bfa25db9e8b8ebcb5f7cf5e5c21c8063986f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "4263effd6a0324af6e29c767d18df0ec9dbfae23119e27d53e6f841929caaa18"
    end
    on_arm do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Linux_arm64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "b51a48723d5f741d02dbb4034fa19c5ca1b78e6a7d46edaf9f6b0cdb0735122f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmhd2spotify"]
    end
  end

  # No zap stanza required
end
