# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmhd2playlist" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "e500d0e4d93b7953159cc6fdb954add2e5e4e2d6b1753ce2b4cc6d4dc3b4fb14"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "82ffa3d2b2e407f12a83072023f1d898356fcd38528e78e6e68ab8915b78df32"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9476e96f10a12b017548177bdfcc6e336b0e84ab4b9f969e891422fcdbe6d8b"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "03c37f28baa2394f518aeadd102bd4f56c3ecd56a3cd043cb697c9c99f0821cb"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "kmhd2playlist"
  desc "Automatically sync songs from KMHD jazz radio to your Spotify playlists"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmhd2playlist"
  manpage "manpages/kmhd2playlist.1.gz"
  bash_completion "completions/kmhd2playlist.bash"
  fish_completion "completions/kmhd2playlist.fish"
  zsh_completion "completions/kmhd2playlist.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmhd2playlist"]
    end
  end

  # No zap stanza required

end
