# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmhd2playlist" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "dbdb086a83b10588b130248f347a75517485b0806b165a2f05f22606ba0606dc"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "8cca58cbff0f1829d6a0595775ef6cb2ba273dae19d1003f7d2dc2d961230265"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6b6e7d99948dc0c402891fd44460fad843c6b829f23013d3c3865f6e17c5f9d"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "7c672deb25cff5889ec5ba7128700027132c37ce2661d2d2dc1b94c607d02903"
      url "https://github.com/toozej/monogo/releases/download/apps/kmhd2playlist/v#{version}/kmhd2playlist_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "kmhd2playlist"
  desc "Automatically sync songs from KMHD jazz radio to your Spotify playlists"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmhd2playlist"
  manpage "manpages/kmhd2playlist.1.gz"
  bash_completion "completions/kmhd2playlist.bash"
  fish_completion "completions/kmhd2playlist.fish"
  zsh_completion "completions/kmhd2playlist.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmhd2playlist"]
    end
  end

  # No zap stanza required

end
