# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmhd2spotify" do
  name "kmhd2spotify"
  desc "Golang starter template"
  homepage "https://github.com/toozej/kmhd2spotify"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmhd2spotify"
  manpage "manpages/kmhd2spotify.1.gz"
  bash_completion "completions/kmhd2spotify.bash"
  zsh_completion "completions/kmhd2spotify.zsh"
  fish_completion "completions/kmhd2spotify.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "bf975255fa3a2b4da04d79c8a276461b2e16d2dd484c825c69f9e70d5aeeeec1"
    end
    on_arm do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "2f2c9fb933c81d17161920f0f4ee9fec5a58bcc41ccabe6382db7622069cbd11"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "2aab70720575b6ba0e9a02425e1c54a4976125f9286e4f90ca8ac809b87b4420"
    end
    on_arm do
      url "https://github.com/toozej/kmhd2spotify/releases/download/v#{version}/kmhd2spotify_Linux_arm64.tar.gz",
        verified: "github.com/toozej/kmhd2spotify/releases/download"
      sha256 "373868f03183a7c499f83d3bd9b020220e47ceca247d9702bcc14bf364dc6fac"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmhd2spotify"]
    end
  end

  # No zap stanza required
end
