# This file was generated by GoReleaser. DO NOT EDIT.
cask "lego-stego" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7847ee5330c054e72a054221494064064b6e7a9286ccbba81e48ee3efae04a81"
      url "https://github.com/toozej/lego-stego/releases/download/v#{version}/lego-stego_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/lego-stego/releases/download"
    end
    on_arm do
      sha256 "4208913a5f288c014d737ac03a2ee93f5493d6ac6d2b3d55093fb91332f42b50"
      url "https://github.com/toozej/lego-stego/releases/download/v#{version}/lego-stego_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/lego-stego/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d4682d0fa3f6961f4f90068994f9c8e0be1da093b202f6fa2ea225e2f8f26d4"
      url "https://github.com/toozej/lego-stego/releases/download/v#{version}/lego-stego_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/lego-stego/releases/download"
    end
    on_arm do
      sha256 "5e741b23a9535cf21089ed8d9540835d21ed3aea12219f5b2d7b73d7f1ef20dd"
      url "https://github.com/toozej/lego-stego/releases/download/v#{version}/lego-stego_Linux_arm64.tar.gz",
        verified: "github.com/toozej/lego-stego/releases/download"
    end
  end

  name "lego-stego"
  desc "Go-based CLI tool for steganography"
  homepage "https://github.com/toozej/lego-stego"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lego-stego"
  manpage "manpages/lego-stego.1.gz"
  bash_completion "completions/lego-stego.bash"
  fish_completion "completions/lego-stego.fish"
  zsh_completion "completions/lego-stego.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lego-stego"]
    end
  end

  # No zap stanza required

end
