# This file was generated by GoReleaser. DO NOT EDIT.
cask "lego-stego" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "21d3ec7f33c3cae09493dfba7402b7313aa467dfc645b632a0af97cdbf477793"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "4b620aaba5786327072417f8222bdf8383798028acd94bd09a981c859f83707e"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "26c2a5e6e6fd51efaee86b6be2eab1e3ee6f652ba154fdfa1e1519e6725956d5"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "2ffe41e5b7a2e1c6c165a49ec32aaebfe2ac0f141e559148ca0a392001165cdd"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "lego-stego"
  desc "Go-based CLI tool for Steganography"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lego-stego"
  manpage "manpages/lego-stego.1.gz"
  bash_completion "completions/lego-stego.bash"
  fish_completion "completions/lego-stego.fish"
  zsh_completion "completions/lego-stego.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lego-stego"]
    end
  end

  # No zap stanza required

end
