# This file was generated by GoReleaser. DO NOT EDIT.
cask "lego-stego" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "bf6713d488efa56d9c9e17a4fc9e4dced6acf1fcb8bb4c09e487c162e0013715"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "abff7f4b7682e72e49385e119ed29c087c7b35146143ac87cc35916c6dfa88c3"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "b94eaa52f45dae81995390a8f256c934a5ebfaa0a17d98689f63f77662d76b7e"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "b8b929927562a5bf8af06273ceb8b168bd20c4ac5c69387276a765440aefbbc0"
      url "https://github.com/toozej/monogo/releases/download/apps/lego-stego/v#{version}/lego-stego_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "lego-stego"
  desc "Go-based CLI tool for Steganography"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lego-stego"
  manpage "manpages/lego-stego.1.gz"
  bash_completion "completions/lego-stego.bash"
  fish_completion "completions/lego-stego.fish"
  zsh_completion "completions/lego-stego.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lego-stego"]
    end
  end

  # No zap stanza required

end
