# This file was generated by GoReleaser. DO NOT EDIT.
cask "photos2map" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "a98c393bb66c435403b6c500dce47b98a429436b24498ba00a08165be835ecbd"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "0914e5ba65e8aa582c229c68834a7493e50a236a44b4f0b395f5a9651f0b4846"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b4bed51dd0f693b0f15f0a7e3ecf9881c0e8746ad0362e22b2c41176d965c8d"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "0341edeb83072264eefa6c1f23d27b68c5da5b82629487da8b7b4619a6a85633"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "photos2map"
  desc "Generate GPX map from photos' EXIF data"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "photos2map"
  manpage "manpages/photos2map.1.gz"
  bash_completion "completions/photos2map.bash"
  fish_completion "completions/photos2map.fish"
  zsh_completion "completions/photos2map.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/photos2map"]
    end
  end

  # No zap stanza required

end
