# This file was generated by GoReleaser. DO NOT EDIT.
cask "photos2map" do
  name "photos2map"
  desc "Generates a map on a HTML page or GPX file from GPS coordinates in images"
  homepage "https://github.com/toozej/photos2map"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "photos2map"
  manpage "man/photos2map.1.gz"
  bash_completion "completions/photos2map.bash"
  zsh_completion "completions/photos2map.zsh"
  fish_completion "completions/photos2map.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/photos2map/releases/download/v#{version}/photos2map_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/photos2map/releases/download"
      sha256 "2372dbf66c9da3e4e9ef1cd6dd254c791b8d91bb23dc74cd73fddd40c7a4ee37"
    end
    on_arm do
      url "https://github.com/toozej/photos2map/releases/download/v#{version}/photos2map_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/photos2map/releases/download"
      sha256 "290b9de644982ee7e0a1005fbaa18a175a8eda87dcd1ace52f17a242bc774162"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/photos2map/releases/download/v#{version}/photos2map_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/photos2map/releases/download"
      sha256 "90eecb2186b7fb55fbfcb46c6c91783f44de80c8b1b80b3148a609c486668677"
    end
    on_arm do
      url "https://github.com/toozej/photos2map/releases/download/v#{version}/photos2map_Linux_arm64.tar.gz",
        verified: "github.com/toozej/photos2map/releases/download"
      sha256 "d04cb3cf84550ce02e5d05d0dfb8a8d5cbe081ae7346305449e2d472eee64235"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/photos2map"]
    end
  end

  # No zap stanza required
end
