# This file was generated by GoReleaser. DO NOT EDIT.
cask "photos2map" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "af4dd2da30074324c9b56cd91833cb877921ccffdcefd5712852e1d730e635b3"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "14b4e143e998d12bf81d70b4996099f22a10cbbaed8b75dcd5d31a6abace1252"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "67d5a7840377ab98209d83c061524c507c9b3e6d44f24c56ad04ba7a727e4f9e"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "c82933c0b8feb9ab3c029ea157d998fafa3fb21cee8634b6c31147806fb6e738"
      url "https://github.com/toozej/monogo/releases/download/apps/photos2map/v#{version}/photos2map_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "photos2map"
  desc "Generate GPX map from photos' EXIF data"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "photos2map"
  manpage "manpages/photos2map.1.gz"
  bash_completion "completions/photos2map.bash"
  fish_completion "completions/photos2map.fish"
  zsh_completion "completions/photos2map.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/photos2map"]
    end
  end

  # No zap stanza required

end
