# This file was generated by GoReleaser. DO NOT EDIT.
cask "podgrab" do
  name "podgrab"
  desc "Self-hosted podcast manager"
  homepage "https://github.com/toozej/podgrab"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podgrab"

  on_macos do
    on_intel do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "0572aefe0fd619006356761a987b13958fa04599bd352231b84a2cb6ccab266c"
    end
    on_arm do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "117d97a9d49139f847ed08f526b1924b9a66060581dd55276c7673a1e9debffc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "91abced08ca837ed7fdf211dc3c61d64470cf3b14c49018db50e446d1faecede"
    end
    on_arm do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Linux_arm64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "f23ae78d36cf6b9d0047b4136a25648458ab5a451a8daad07614c4f7edf45e71"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podgrab"]
    end
  end

  # No zap stanza required
end
