# This file was generated by GoReleaser. DO NOT EDIT.
cask "podgrab" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "7b88a91ed7318a0999c6449b364bd5a462a6132a98ec37a9dbc48426a56ba30f"
    end
    on_arm do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "f509b3b050b541d063e0da042907043a33ac6c65f7c8feae5080bee1b776efe4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "206f042f2e8fbec3b6d7faec705c251b9134654d142ebb45eacb5502d79755ae"
    end
    on_arm do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Linux_arm64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "ce6a90581e2e1939a21f71405bf39e71ecdded87cc1d10e96f3cb709a62e4cc6"
    end
  end

  name "podgrab"
  desc "Self-hosted podcast manager"
  homepage "https://github.com/toozej/podgrab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podgrab"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podgrab"]
    end
  end

  # No zap stanza required

end
