# This file was generated by GoReleaser. DO NOT EDIT.
cask "podgrab" do
  name "podgrab"
  desc "Self-hosted podcast manager"
  homepage "https://github.com/toozej/podgrab"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podgrab"

  on_macos do
    on_intel do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "db06a1e04409c4696b2a87b27142961093919384315e32d2ec9a9b144f41f9cd"
    end
    on_arm do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "c577274d75b7064b8339f89b5beb8b7fce469e71b48eea5f97699b08fe0246f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "dacff1eb41b8a6bc7737f2ee13dc8ad5a1a0f29fcd673ee1344189d200bce19b"
    end
    on_arm do
      url "https://github.com/toozej/podgrab/releases/download/v#{version}/podgrab_Linux_arm64.tar.gz",
        verified: "github.com/toozej/podgrab/releases/download"
      sha256 "f42c3f0f877be7c7f7d625b58e45b41b247c7ccabc1d624baf36bff75559ef97"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podgrab"]
    end
  end

  # No zap stanza required
end
