# This file was generated by GoReleaser. DO NOT EDIT.
cask "readme-gen" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e25cd2539031b4947d576976320dfb0755f27bfb285c88a598388f50cb53c204"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "232d5ff09b95177eb03fd078ff3b3ca5b3a553d2ee9beaafb5178844b79c0ffd"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e9f50e736b859f6dc56b33df23dc7f09f943c26636f1fb5102c7c6821002d74"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "944f9ebc8189fd1543eb44ee787921fe143993abce97b6c5a090f61bd1f3e2ee"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "readme-gen"
  desc "Generate GitHub profile README.md files from recent public activity"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readme-gen"
  manpage "manpages/readme-gen.1.gz"
  bash_completion "completions/readme-gen.bash"
  fish_completion "completions/readme-gen.fish"
  zsh_completion "completions/readme-gen.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/readme-gen"]
    end
  end

  # No zap stanza required

end
