# This file was generated by GoReleaser. DO NOT EDIT.
cask "readme-gen" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "7d43e2bab216f4764fa5cc81cecf27734a79aeb27df1ac3339b2322274e33474"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "fd1f1fb73486c8af56e4b5eda2e3f67410799891905da1b31b1c629ddc7781b1"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "788b8d379480a2101f962b424585ae29b354d0b5cb09566d3b37d4851707e4e2"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "2ccd65cfad6d10bec13bd163e053aa30ab2dcefc1ca9ff8a3b3da8114aee363c"
      url "https://github.com/toozej/monogo/releases/download/apps/github-readme-gen/v#{version}/github-readme-gen_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "readme-gen"
  desc "Generate GitHub profile README.md files from recent public activity"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readme-gen"
  manpage "manpages/readme-gen.1.gz"
  bash_completion "completions/readme-gen.bash"
  fish_completion "completions/readme-gen.fish"
  zsh_completion "completions/readme-gen.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/readme-gen"]
    end
  end

  # No zap stanza required

end
