# This file was generated by GoReleaser. DO NOT EDIT.
cask "rssffs" do
  name "rssffs"
  desc "RSS Feed Finder [and] Subscriber"
  homepage "https://github.com/toozej/RSSFFS"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rssffs"
  manpage "man/RSSFFS.1.gz"
  bash_completion "completions/RSSFFS.bash"
  zsh_completion "completions/RSSFFS.zsh"
  fish_completion "completions/RSSFFS.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "6912fd4d1c395450a4161a00ac2f3de71358441294a255d7dea7d9f6e5525a56"
    end
    on_arm do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "3c227ef95f5236638642ee67646f0cbbfd6200d5a7183fd7f7b4335193058e7b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "74726c85388fd6092b4a3392ba1f7b67b3b1a6e33f5beb9433bc5e9db77a5660"
    end
    on_arm do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Linux_arm64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "6a077e520d29b7f7ac6701a2418769275fd3a57f2885989c50fce30939e07e55"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/RSSFFS"]
    end
  end

  # No zap stanza required
end
