# This file was generated by GoReleaser. DO NOT EDIT.
cask "rssffs" do
  name "rssffs"
  desc "RSS Feed Finder [and] Subscriber"
  homepage "https://github.com/toozej/RSSFFS"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rssffs"
  manpage "man/RSSFFS.1.gz"
  bash_completion "completions/RSSFFS.bash"
  zsh_completion "completions/RSSFFS.zsh"
  fish_completion "completions/RSSFFS.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "129a1b6abb6d4f221e20384beb7f85c27bcd5ed382e6a516fdab8628ae05b01f"
    end
    on_arm do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "1d3f7ec6571c54f47cbf44a8708c51ccf6721bb794d29d80226182ec6cf7fc85"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "7a4f64f9dda610f2bbbdedda6eb6df28f7a12342483a99d7df87405e39cfc5de"
    end
    on_arm do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Linux_arm64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "6f0c362ce9a11f4a1aa284710dff766b71103af8acdc8500ab7760b80e5a4d8f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/RSSFFS"]
    end
  end

  # No zap stanza required
end
