# This file was generated by GoReleaser. DO NOT EDIT.
cask "rssffs" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "006eecda02a09d2b99544b6794443f3449b482b49ebbc4bec62cfb4ac3487b24"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "3ca0f8b17d88f1cf7880078874cd4b77426f52fae5f9fcf74daec8332ecac27b"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "b27598e4af477f700ee899d0f1e1f4dc1d2575800bc46a816839f19e7b4e08fb"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "b9ddafb35f4bb6bd9ddd6afa5b1539840800daeaee3c212e017101a59df7f9e8"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "rssffs"
  desc "RSS Feed Finder [and] Subscriber"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "RSSFFS"
  manpage "manpages/RSSFFS.1.gz"
  bash_completion "completions/RSSFFS.bash"
  fish_completion "completions/RSSFFS.fish"
  zsh_completion "completions/RSSFFS.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/RSSFFS"]
    end
  end

  # No zap stanza required

end
