# This file was generated by GoReleaser. DO NOT EDIT.
cask "rssffs" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "bc1bfa69c1fccc7caf0129ebd191d64ad10b18b635128d8c97223bd0999ffe30"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "3c952e17db8bfaf228a63e40d20c1f703fde3345984242747c4e138be39892cb"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "7964de5db20eb413e276c1fbe9fb294ffc6c1fcdfa8eee9d1e8fd9cc81f00a77"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "122cfe6d3b1a749a62ec605475e7178af392239e5ff2099c477c8ed9846e27f7"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "rssffs"
  desc "RSS Feed Finder [and] Subscriber"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "RSSFFS"
  manpage "manpages/RSSFFS.1.gz"
  bash_completion "completions/RSSFFS.bash"
  fish_completion "completions/RSSFFS.fish"
  zsh_completion "completions/RSSFFS.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/RSSFFS"]
    end
  end

  # No zap stanza required

end
