# This file was generated by GoReleaser. DO NOT EDIT.
cask "rssffs" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "2525432c79ef18081a82b7cab12d1a292672c3a9f739ef5e3b811c162a83129a"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "c1e19f2192185006aa91dcb5341afb2f40d3a1a7b0b2200b4248d0adacb25164"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd4dc2156c7df6053d7808bb8c7e80579098f3b15ce65a962cc4b305a25382e1"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "2c32552a71033c461c5a94df8f659a7c0725984624fbc70a59625e09671af172"
      url "https://github.com/toozej/monogo/releases/download/apps/RSSFFS/v#{version}/RSSFFS_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "rssffs"
  desc "RSS Feed Finder [and] Subscriber"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "RSSFFS"
  manpage "manpages/RSSFFS.1.gz"
  bash_completion "completions/RSSFFS.bash"
  fish_completion "completions/RSSFFS.fish"
  zsh_completion "completions/RSSFFS.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/RSSFFS"]
    end
  end

  # No zap stanza required

end
