# This file was generated by GoReleaser. DO NOT EDIT.
cask "rssffs" do
  name "rssffs"
  desc "RSS Feed Finder [and] Subscriber"
  homepage "https://github.com/toozej/RSSFFS"
  version "1.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rssffs"
  manpage "manpages/RSSFFS.1.gz"
  bash_completion "completions/RSSFFS.bash"
  zsh_completion "completions/RSSFFS.zsh"
  fish_completion "completions/RSSFFS.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "b65d2304159bf226592c88f9312b72082cf9f9938823d78c607a35162384f53d"
    end
    on_arm do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "ab2ba16492cbd40313a64c8479979d9d062e9d93f81546fc4864e9b803989268"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "8b23eec4f894c2bdc817d42145233045274d5fcaa57da8d9babd5a65384f54d2"
    end
    on_arm do
      url "https://github.com/toozej/RSSFFS/releases/download/v#{version}/RSSFFS_Linux_arm64.tar.gz",
        verified: "github.com/toozej/RSSFFS/releases/download"
      sha256 "89d1530a602bf4faf724a631e290db704ac2a46bfb9d4d5a4741067e2f62ce5c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/RSSFFS"]
    end
  end

  # No zap stanza required
end
