# This file was generated by GoReleaser. DO NOT EDIT.
cask "terranotate" do
  name "terranotate"
  desc "Terraform Comment Parser and Validator"
  homepage "https://github.com/toozej/terranotate"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terranotate"
  manpage "manpages/terranotate.1.gz"
  bash_completion "completions/terranotate.bash"
  zsh_completion "completions/terranotate.zsh"
  fish_completion "completions/terranotate.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "a90f43f7c7b3d834316baa3c19a2fcd86ad3353d8e39019e1c982663328d56da"
    end
    on_arm do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "8d3758c4fe7a556b80c00cdb9598e9584a223feb55ef953c76c656e350931396"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "8371d1f5f1a187e98673d164ca428db9ec2ccf5f7828ec73499b8cec02732bc5"
    end
    on_arm do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Linux_arm64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "0c8bfae85acba78925788346ac845b14bbf6c5e35c4ff71578f6962bbfba52ee"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terranotate"]
    end
  end

  # No zap stanza required
end
