# This file was generated by GoReleaser. DO NOT EDIT.
cask "terranotate" do
  name "terranotate"
  desc "Terraform Comment Parser and Validator"
  homepage "https://github.com/toozej/terranotate"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terranotate"
  manpage "man/terranotate.1.gz"
  bash_completion "completions/terranotate.bash"
  zsh_completion "completions/terranotate.zsh"
  fish_completion "completions/terranotate.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "f1193c4afa04c2c353299adcf0dc4dd8f6c02a86ccd67d4835c6912c1db20b8c"
    end
    on_arm do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "e554f24fcf259a78c5de78850a097aa34fbf7ad040ba42630553f97e7a53160b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "417337d644f663b14f047961107c3cdd0f5e9722e533c492612a552154882d89"
    end
    on_arm do
      url "https://github.com/toozej/terranotate/releases/download/v#{version}/terranotate_Linux_arm64.tar.gz",
        verified: "github.com/toozej/terranotate/releases/download"
      sha256 "21a73c73a3f17315d44472057af783c9f80d23228ae1c2468b75df3699d785a0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terranotate"]
    end
  end

  # No zap stanza required
end
