# This file was generated by GoReleaser. DO NOT EDIT.
cask "terranotate" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9d7e2e393b8be563462bd9e176c8ccb3906493abccf3f8bd66592328a18b3b55"
      url "https://github.com/toozej/monogo/releases/download/apps/terranotate/v#{version}/terranotate_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "bf3cd8268751838179f6d19538dca9bab54b836a4f7e66456d4d4b55b6222762"
      url "https://github.com/toozej/monogo/releases/download/apps/terranotate/v#{version}/terranotate_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "0c07fad3d4e646a997dfd5815081f6c5c9eba9b4437db0532af991bccac47515"
      url "https://github.com/toozej/monogo/releases/download/apps/terranotate/v#{version}/terranotate_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "0ef44240013e44ed6fa3165be3431a960a591e238dc382ae6d67f80d9b81b6a2"
      url "https://github.com/toozej/monogo/releases/download/apps/terranotate/v#{version}/terranotate_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "terranotate"
  desc "Terraform Comment Parser and Validator"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terranotate"
  manpage "manpages/terranotate.1.gz"
  bash_completion "completions/terranotate.bash"
  fish_completion "completions/terranotate.fish"
  zsh_completion "completions/terranotate.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terranotate"]
    end
  end

  # No zap stanza required

end
