# This file was generated by GoReleaser. DO NOT EDIT.
cask "trails-completionist" do
  name "trails-completionist"
  desc "tools for tracking completion of trails"
  homepage "https://github.com/toozej/trails-completionist"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trails-completionist"
  manpage "man/trails-completionist.1.gz"
  bash_completion "completions/trails-completionist.bash"
  zsh_completion "completions/trails-completionist.zsh"
  fish_completion "completions/trails-completionist.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "a6aa271644beeedb580ce1f7c48c65d4b190c22eb01d5c08b1e679d0f6eaa4e2"
    end
    on_arm do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "51f9ca160bde75075e0015751339ee72ea5ebd5a608b998621d8ffe784d055fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "7add99785297b5144ec831c9647c123b727b48fcd159cc74d33c0d1b3ecf6634"
    end
    on_arm do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Linux_arm64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "e6c7c926143b2fe3e5d49e44c999e1dbff6263d5b77754aa7d95369c51faff5a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trails-completionist"]
    end
  end

  # No zap stanza required
end
