# This file was generated by GoReleaser. DO NOT EDIT.
cask "trails-completionist" do
  name "trails-completionist"
  desc "tools for tracking completion of trails"
  homepage "https://github.com/toozej/trails-completionist"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trails-completionist"
  manpage "manpages/trails-completionist.1.gz"
  bash_completion "completions/trails-completionist.bash"
  zsh_completion "completions/trails-completionist.zsh"
  fish_completion "completions/trails-completionist.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "6cc230eb91ca2da4ad74b20f37680390a10db88d77e5aa14c615e9e0b831d4f7"
    end
    on_arm do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "fd9a394184592c14ebe0e3896cc4719ffb2b5579374f178620d531dfc666aa2b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "e2683728d43adfef89ab9ada2a0b33dc7e5496386326487fd94d2f67ceadec2a"
    end
    on_arm do
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Linux_arm64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
      sha256 "841e8969d61adc95f9ea371110a363f1bc14c11542736227e8f15adde9282f4f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trails-completionist"]
    end
  end

  # No zap stanza required
end
