# This file was generated by GoReleaser. DO NOT EDIT.
cask "trails-completionist" do
  version "2.1.2"

  on_macos do
    on_intel do
      sha256 "a5bae280a3e6a4a640d8b5b6136098ac4a3bfc5d71678f7b682d05974a1b4932"
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
    end
    on_arm do
      sha256 "77510a63f9fe458442c61c6b28d41f31adc2324e7e94c815da9535ff37d07142"
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "b6490aec695b6d7758568240f4239a0c14caed8fae69d76e5881e557308dfc7a"
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
    end
    on_arm do
      sha256 "6b02ce2fd7097d8b7adbfaaf2185eca8030a8de5e872d28f17cfeb6d1096ab44"
      url "https://github.com/toozej/trails-completionist/releases/download/v#{version}/trails-completionist_Linux_arm64.tar.gz",
        verified: "github.com/toozej/trails-completionist/releases/download"
    end
  end

  name "trails-completionist"
  desc "tools for tracking completion of trails"
  homepage "https://github.com/toozej/trails-completionist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trails-completionist"
  manpage "manpages/trails-completionist.1.gz"
  bash_completion "completions/trails-completionist.bash"
  fish_completion "completions/trails-completionist.fish"
  zsh_completion "completions/trails-completionist.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trails-completionist"]
    end
  end

  # No zap stanza required

end
