# This file was generated by GoReleaser. DO NOT EDIT.
cask "url2anki" do
  name "url2anki"
  desc "Generate Anki flashcards from a URL"
  homepage "https://github.com/toozej/url2anki"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "url2anki"
  manpage "man/url2anki.1.gz"
  bash_completion "completions/url2anki.bash"
  zsh_completion "completions/url2anki.zsh"
  fish_completion "completions/url2anki.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "0573483041a52dbab1f4713328015af099f39a18a68b4f056748d44b12837ed8"
    end
    on_arm do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "d7c1ca756cc2bf5041fdbf712721ae24e53c65020471f9c2d175417123cd746d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "1c4806b41b8afca9001d7c86675eeac955e79bf2b7672d8a52473f1ffeef0d89"
    end
    on_arm do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Linux_arm64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "4b663157f135540230c871a21a34ffe1290a6d9153ebda1c4bd61c35497d3ab0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/url2anki"]
    end
  end

  # No zap stanza required
end
