# This file was generated by GoReleaser. DO NOT EDIT.
cask "url2anki" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "c7cc0394e85e3236c921e0e5e3c93ed8e4eae0795c380516d9800605341ecd81"
      url "https://github.com/toozej/monogo/releases/download/apps/url2anki/v#{version}/url2anki_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "cccddd9370e564a8df4f3a6f3ef3322ee17fbad0d06564238a6e7aefc39e00d8"
      url "https://github.com/toozej/monogo/releases/download/apps/url2anki/v#{version}/url2anki_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "87c07e6b4d0463127e62a1b5d293ee81ffcfd11688c1e312a4912fbda5072869"
      url "https://github.com/toozej/monogo/releases/download/apps/url2anki/v#{version}/url2anki_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
    on_arm do
      sha256 "53b3ca06383737199c0e5e6c5cf0ef95d5660f1766127dd058f0d1c9c498f676"
      url "https://github.com/toozej/monogo/releases/download/apps/url2anki/v#{version}/url2anki_Linux_arm64.tar.gz",
        verified: "github.com/toozej/monogo/releases/download"
    end
  end

  name "url2anki"
  desc "Generate Anki flashcards from a URL"
  homepage "https://github.com/toozej/monogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "url2anki"
  manpage "manpages/url2anki.1.gz"
  bash_completion "completions/url2anki.bash"
  fish_completion "completions/url2anki.fish"
  zsh_completion "completions/url2anki.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/url2anki"]
    end
  end

  # No zap stanza required

end
