# This file was generated by GoReleaser. DO NOT EDIT.
cask "url2anki" do
  name "url2anki"
  desc "Generate Anki flashcards from a URL"
  homepage "https://github.com/toozej/url2anki"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "url2anki"
  manpage "manpages/url2anki.1.gz"
  bash_completion "completions/url2anki.bash"
  zsh_completion "completions/url2anki.zsh"
  fish_completion "completions/url2anki.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "19923b27ae3f2ce032afe3d39819b7f8711d3b4bf30862bd42e1410e5891b78b"
    end
    on_arm do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "fe2a2f39e9b5ac9a600cd4b4882e471b013c2743c0c6b53a91a041fbd4b49a42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "1c99aafb285f58faa630b8383b4f6646fabbb3524187a322777d1d40f36ae742"
    end
    on_arm do
      url "https://github.com/toozej/url2anki/releases/download/v#{version}/url2anki_Linux_arm64.tar.gz",
        verified: "github.com/toozej/url2anki/releases/download"
      sha256 "d048756251f81f911837ae4c86e8933fb2b812b7c3935f309d4ab9d007568a18"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/url2anki"]
    end
  end

  # No zap stanza required
end
