# This file was generated by GoReleaser. DO NOT EDIT.
cask "waffles" do
  name "waffles"
  desc "LLM toolchain orchestrator for local development workflows"
  homepage "https://github.com/toozej/waffles"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waffles"
  manpage "manpages/waffles.1.gz"
  bash_completion "completions/waffles.bash"
  zsh_completion "completions/waffles.zsh"
  fish_completion "completions/waffles.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "86dde8d2b34d529431ca2e1665c6c4aaaed23824a0771f11e90f3fa6632189d0"
    end
    on_arm do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "9e1bc6319c17b7a9bf11c61f7487875da6b9db2f42c519fc584a716db67e41cb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "7994d38c5f460514bdbcf3df2ef9c8a140caff2bd38b7b81496908ed31797733"
    end
    on_arm do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Linux_arm64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "b9068353d8eb9fd4cb2faebc92be2077fdb08e1193dc2e4d643b1fa6b833c576"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waffles"]
    end
  end

  # No zap stanza required
end
