# This file was generated by GoReleaser. DO NOT EDIT.
cask "waffles" do
  name "waffles"
  desc "LLM toolchain orchestrator for local development workflows"
  homepage "https://github.com/toozej/waffles"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waffles"
  manpage "man/waffles.1.gz"
  bash_completion "completions/waffles.bash"
  zsh_completion "completions/waffles.zsh"
  fish_completion "completions/waffles.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "9eecee6e257e55311b0b574972246bd750683950c8990191ecbde136e54e4b9b"
    end
    on_arm do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "bfaea44742da13dde21268358b6378264c9919cc6e0540099fcb2794fd79b2e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "fb13a83eb53ba3943f8967beb70aa7d190f417f54bc7daac45cd9b26fce22a94"
    end
    on_arm do
      url "https://github.com/toozej/waffles/releases/download/v#{version}/waffles_Linux_arm64.tar.gz",
        verified: "github.com/toozej/waffles/releases/download"
      sha256 "4006a4814f73ff7abd682cbcbf1e3181fe72c2259c490fae721d69719f8fa137"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waffles"]
    end
  end

  # No zap stanza required
end
