# This file was generated by GoReleaser. DO NOT EDIT.
cask "wheresmyprompt" do
  name "wheresmyprompt"
  desc "Find liquor stores and their inventory"
  homepage "https://github.com/toozej/wheresmyprompt"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wheresmyprompt"
  manpage "man/wheresmyprompt.1.gz"
  bash_completion "completions/wheresmyprompt.bash"
  zsh_completion "completions/wheresmyprompt.zsh"
  fish_completion "completions/wheresmyprompt.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "a7d4a348165131798174799aaa89a542bbb92b45186a9fe58d47600bb0eeb0c3"
    end
    on_arm do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "30453666fe19ceb17c45f720f466962218469dc3d42a81f3cd3cedc08b30b708"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "feb62612c48aba0bd8be4dce430706ac5d9ce7eaf6052e20e1b8718a8b057c02"
    end
    on_arm do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Linux_arm64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "22b0b175304a46e08f1c92c1f7c1596dd144f22f6e3b63516c10b69095bedecc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wheresmyprompt"]
    end
  end

  # No zap stanza required
end
