# This file was generated by GoReleaser. DO NOT EDIT.
cask "wheresmyprompt" do
  name "wheresmyprompt"
  desc "Find liquor stores and their inventory"
  homepage "https://github.com/toozej/wheresmyprompt"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wheresmyprompt"
  manpage "manpages/wheresmyprompt.1.gz"
  bash_completion "completions/wheresmyprompt.bash"
  zsh_completion "completions/wheresmyprompt.zsh"
  fish_completion "completions/wheresmyprompt.fish"

  on_macos do
    on_intel do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Darwin_x86_64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "70ab6c3e35fc739afe1a3d2a3164661209c30f72b72eaa773de4e4645bfab642"
    end
    on_arm do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Darwin_arm64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "250f0e4d72aeab5357f3cd91e9ba770b2ee26e2384b6f96736b6e9c8cb71b744"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Linux_x86_64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "874ed1b39bd7a9ef56d5ced2e2c532ff48a9365d988c309834e1557c38907af0"
    end
    on_arm do
      url "https://github.com/toozej/wheresmyprompt/releases/download/v#{version}/wheresmyprompt_Linux_arm64.tar.gz",
        verified: "github.com/toozej/wheresmyprompt/releases/download"
      sha256 "e19967dec96d4baf5863518bd8548570ee75201a0bdae60fca273996c035ded7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wheresmyprompt"]
    end
  end

  # No zap stanza required
end
